### ISSUE TITLE
Questions about the experiments

### ISSUE THREAD

**Issue by La-SilverLand** [XuezheMax/fairseq-apollo#3]
hi, i've got some question about the experiments
1. for the GLUE tasks, 
- the sequences in GLUE tasks are relatively small, the LUNA-128 result is reported, how about the LUNA-16 result ?
- only 3 tasks in GLUE are listed, why not list all the task scores

2. about the contextual information in P
when you compared the two implementations of P ( as the input of the model VS learnable parameter of each layer), only on the translation task, it's not significant enough to judge, do you have any results on the other tasks, like LRA ?

**Comment by XuezheMax** [comment]
Hi,

Thanks for your questions:
For GLUE tasks, we only trained a Luna-BERT model with 512-128 setting where 512 is the length of input segments and 128 is the projection length. Since training BERT-level model is time and gpu consuming, we did not run Luna-16 on it.
The other GLUE tasks except the 3 reported in our paper are based on the MNLI dataset, which is relatively large. We will report their results in our next version.

For two versions of P, we believe MT is the most significant task to compare since it involves both encoder and decoder. For other tasks like LRA, the non-contextual version of P (learnable parameter) is very similar to Linformer (though not exactly the same). The comparison with Linformer on LRA and pre-training has been reported in our paper.
