### ISSUE TITLE
Add another comparison: AdamW on the language modeling

### ISSUE THREAD

**Issue by sherlcok314159** [XuezheMax/fairseq-apollo#7]
Nice Work! But I wonder how the AdamW performs on the same settings.

**Comment by XuezheMax** [comment]
Hi,

Sorry for the late reply. If I understand your question correctly, you asked for comparing Apollo with AdamW on language modeling?
 In our Table 2 and Figure3, we compare with Adam and its variants on language modeling. Since in all LM experiments, we used `weight-decay=0.0`, Adam is equivalent to AdamW.
